### ISSUE TITLE
Pre-stiched nd2

### ISSUE THREAD

**Issue by raanreye** [SydShafferLab/StitchWell#1]
Currently the code can't handle pre-stiched nd2 files
Bellow is an example on how to get a all the tif files from the pre-stiched nd2 files

"""
from nd2reader import ND2Reader
from tifffile import imwrite
import os

paths_im = glob.glob("path/to/stiched_nd2_folder")

for i in paths_im:
    with ND2Reader(i) as images:
        imwrite(os.path.join(i,i.replace('.nd2','.tif')),images[0],ome=True,photometric='minisblack')
""""

**Comment by zjniu** [comment]
This issue has been fixed with 5c4883bd99f1eddc006d9491742d77a03d834b7b.
